name: Music Assistant Alexa API
version: "1.0.7"
slug: ma_alexa_api
description: Music Assistant Alexa API
url: "https://github.com/3kinocx974/Alexa-api/tree/main/music-assistant-alexa-api"
arch:
  - aarch64
  - amd64
init: false
hassio_api: true
hassio_role: manager
options:
  api_username: "ma-local-alexa-api"
  ha_token: ""
schema:
  ma_hostname: "str"
  api_username: "str"
  api_password: "password?"
  aws_default_region: "str?"
  ha_token: "password?"
webui: "[PROTO:option_name]://[HOST]:[PORT:5000]/status"
stage: experimental
homeassistant: 2025.12.5
ports:
  5000/tcp: 5000
ports_description:
  5000/tcp: "The API port"
